### ISSUE TITLE
Create database to save Picture for transfer learning of the model

### ISSUE THREAD

**Issue by LorenzoPinto04** [FedericoFogolin/demandator#12]
Create Database with sqlite module to:

- Keep track of all the calls sent by each users 

- Keep track of every image sent (save it in database as blob)

- Keep track of each results 

- Signal every low prediction to be able to manually label images that can eventually used for transfer learning in the model retraining

**Comment by FabioDeBenetti** [comment]
Solved in 2ff0ce43d0de3e2079294738beae9e732d7d2d04
