### ISSUE TITLE
Create/Modify Readme.md and License for the package and the main.

### ISSUE THREAD

**Issue by enricodarodda** [FedericoFogolin/demandator#18]
Create the Readme.md file for the main function, with a complete description of the functionality and how it should be used, so listing all the parameters etc. Verify if there is the need of a new license.
Modify the Readme.md file inside the demandator_pkg package and verify if the license is correct.

**Comment by LorenzoPinto04** [comment]
solved with commit 8fda23857c52a55cb7c9b12d1cbc8f9f96b3dce8
