### ISSUE TITLE
Refactoring 'Demandator' code

### ISSUE THREAD

**Issue by FabioDeBenetti** [FedericoFogolin/demandator#2]
- Re-write 'Demandator' function;
- Make that function PEP8 compliant.
- make the function return something instead of using the print() statement

**Comment by enricodarodda** [comment]
set the variable type of each add_argument entry, in order not to incur in misunderstandings

**Comment by FabioDeBenetti** [comment]
Solved in 51873fc3663c6d02e9d43d081f6b28396b32786f
