### ISSUE TITLE
Insert parameter that handles maximum number of predictions

### ISSUE THREAD

**Issue by enricodarodda** [FedericoFogolin/demandator#9]
insert in the main.py file a parameter that handles the maximum number of predictions retrieved by the api. make it a "optional" but not required. handle in advance the number of results (il più probabile) and let the user decide if he/she wants more. If there are more results to be displayed, order them from the most probable to the least.

**Comment by LorenzoPinto04** [comment]
Solved in commit c1873548d15df69c141535d460d7d7d5c063830d
